# Generated by Django 5.1.6 on 2025-02-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_candidate_options_alter_constituency_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='number_of_voters',
        ),
    ]
