# Generated by Django 5.1.6 on 2025-02-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_candidate_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='verified',
            new_name='voted',
        ),
    ]
