# Generated by Django 5.1.6 on 2025-02-10 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.voter')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.candidate')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.constituency')),
            ],
        ),
    ]
