# Generated by Django 5.1.6 on 2025-02-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
    ]
